---
# Determine if the test hosts exist.
# Check vmware to see if vm exists
# Ensure host is powered on
# Ensure we can resolve the host
# Ensure we can collect the facts
# if any of this fails, set rebuild_instances
#  If they are up, see if they are installed
#   If they are installed see if they have snapshots
#      If they have snapshots rollback the snapshots
#         return success
#      If they don't have snapshots
#         return failure
#
# If any step fails or there are no snapshots we will fail
# Failure will invoke rebuild in the workflow

- name: Check if hosts exist by getting facts
  hosts: all
  gather_facts: false

  tasks:
  
  - name: "Performing DNS lookup on the host - {{ inventory_hostname }}"
    command: "nslookup {{ inventory_hostname }}"

  - name: "Power-on vm - {{ inventory_hostname }}"
    include_tasks: vmware/tasks/power_action.yml
    vars:
    - force: true
    delegate_to: 127.0.0.1

  - name: "Wait for max 300s system to respond to SSH"
    wait_for:
      timeout: 300s
      sleep: 15
      port: 22
      host: "{{ inventory_hostname }}"
      search_regex: OpenSSH
    connection: local

  - name: Ping the host
    ansible.builtin.ping:
      data: "{{ ansible_fqdn }} is alive"
    gather_facts: true
  
  - name: Check to see if we have the install checkpoint set
  